/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_link_storage_jni_JniClient */

#ifndef _Included_com_link_storage_jni_JniClient
#define _Included_com_link_storage_jni_JniClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_link_storage_jni_JniClient
 * Method:    addStr
 * Signature: (Lcom/link/storage/jni/Mode;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_link_storage_jni_JniClient_addStr
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_link_storage_jni_JniClient
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_link_storage_jni_JniClient_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
